---
swagger: "2.0"
info:
  title: IDF Quotes
  description: Service to create and manage quotes
  contact:
    email: tom.redfern@gmail.com
  version: "0.1"
schemes:
- https
- http
paths:
  /quotes:
    post:
      summary: Creates a quote
      description: Creates a quote
      operationId: aldint-api-create-quote
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: quote
        in: body
        description: Quote input DTO
        schema:
          $ref: '#/definitions/quoteType'
      responses:
        200:
          description: Quote created!
        400:
          description: Invalid input
        500:
          description: Internal service problem. Do not retry call.
        503:
          description: Internal service problem. Retrying of call is allowed.
  /quotes/{quoteId}:
    get:
      summary: Gets a quote.
      operationId: aldint-api-quote-get
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: quoteId
        in: path
        required: true
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/quoteType'
        404:
          description: Quote not found.
        500:
          description: Internal service problem. Do not retry call.
        503:
          description: Internal service problem. Retrying of call is allowed.
  /quotes/customers/{customerId}:
    get:
      summary: Gets all quote for a customer.
      operationId: aldint-api-customerquotes-get
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: customerId
        in: path
        required: true
        type: string
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/customerQuotesType'
        201:
          description: Customer found but no quotes exist for the customer.
        404:
          description: Customer not found.
        500:
          description: Internal service problem. Do not retry call.
        503:
          description: Internal service problem. Retrying of call is allowed.
definitions:
  customerQuotesType:
    type: array
    items:
      type: object
      properties:
        customerId:
          description: Internal customer ID
          type: integer
        quoteId:
          description: Internal quote ID
          type: integer
  quoteType:
    required:
    - customerId
    - status
    type: object
    properties:
      quoteRef:
        description: Quote external or customer identifier
        type: string
      vehicleQuoteId:
        format: uuid
        description: For quotes based on vehicle search precalculation, the VehicleQuoteId
          of the Vehicle Quote Fact.
        type: integer
      customerId:
        description: The associated customer. *Assumes there is always a customer*.
        type: integer
      pricing:
        $ref: '#/definitions/pricingType'
      status:
        description: Describes the state the quote is in. This is an internal state
          and does not necessarily map onto other models.
        default: New
        enum:
        - New
        - Approved
        - Rejected
        - Completed
        - Abandoned
        type: string
      data:
        description: A bag for any other properties needed
        type: array
        items:
          type: object
          properties:
            key:
              type: string
            value:
              type: string
  pricingType:
    description: A common set of fields for lease pricing
    type: object
    properties:
      term:
        required:
        - quantity
        - period
        type: object
        properties:
          period:
            description: Period duration
            default: month
            enum:
            - day
            - week
            - month
            - quarter
            - year
            type: string
          quantity:
            description: the number of periods which constitute the contract term
            type: number
      mileage:
        description: The permitted mileage. Mileage may also be expressed in km.
        required:
        - distance
        - unit
        type: object
        properties:
          unit:
            enum:
            - mi
            - km
            type: string
          distance:
            type: integer
      cost:
        description: The cost in terms of currency and amount per period
        required:
        - currency
        - amount
        - perPeriod
        type: object
        properties:
          currency:
            description: ISO currency code
            maxLength: 3
            minLength: 3
            type: string
          amount:
            type: number
          perPeriod:
            default: month
            enum:
            - day
            - week
            - month
            - quarter
            - year
            type: string
